export const POS_AGE_GROUPS = ['0-10', '11-18', '19-25', '25-40', '40-50+'] as const;

// Canonical values stored on CustomerProfile. Keep the ISO code alongside the
// label so clients can sort, search, and localize without changing stored data.
export const POS_NATIONALITIES = [
  { code: 'AF', label: 'Afghan' },
  { code: 'AL', label: 'Albanian' },
  { code: 'DZ', label: 'Algerian' },
  { code: 'AD', label: 'Andorran' },
  { code: 'AO', label: 'Angolan' },
  { code: 'AG', label: 'Antiguan and Barbudan' },
  { code: 'AR', label: 'Argentine' },
  { code: 'AM', label: 'Armenian' },
  { code: 'AU', label: 'Australian' },
  { code: 'AT', label: 'Austrian' },
  { code: 'AZ', label: 'Azerbaijani' },
  { code: 'BS', label: 'Bahamian' },
  { code: 'BH', label: 'Bahraini' },
  { code: 'BD', label: 'Bangladeshi' },
  { code: 'BB', label: 'Barbadian' },
  { code: 'BY', label: 'Belarusian' },
  { code: 'BE', label: 'Belgian' },
  { code: 'BZ', label: 'Belizean' },
  { code: 'BJ', label: 'Beninese' },
  { code: 'BT', label: 'Bhutanese' },
  { code: 'BO', label: 'Bolivian' },
  { code: 'BA', label: 'Bosnian and Herzegovinian' },
  { code: 'BW', label: 'Botswanan' },
  { code: 'BR', label: 'Brazilian' },
  { code: 'BN', label: 'Bruneian' },
  { code: 'BG', label: 'Bulgarian' },
  { code: 'BF', label: 'Burkinabe' },
  { code: 'BI', label: 'Burundian' },
  { code: 'CV', label: 'Cabo Verdean' },
  { code: 'KH', label: 'Cambodian' },
  { code: 'CM', label: 'Cameroonian' },
  { code: 'CA', label: 'Canadian' },
  { code: 'CF', label: 'Central African' },
  { code: 'TD', label: 'Chadian' },
  { code: 'CL', label: 'Chilean' },
  { code: 'CN', label: 'Chinese' },
  { code: 'CO', label: 'Colombian' },
  { code: 'KM', label: 'Comorian' },
  { code: 'CG', label: 'Congolese' },
  { code: 'CD', label: 'Congolese (DRC)' },
  { code: 'CR', label: 'Costa Rican' },
  { code: 'CI', label: 'Ivorian' },
  { code: 'HR', label: 'Croatian' },
  { code: 'CU', label: 'Cuban' },
  { code: 'CY', label: 'Cypriot' },
  { code: 'CZ', label: 'Czech' },
  { code: 'DK', label: 'Danish' },
  { code: 'DJ', label: 'Djiboutian' },
  { code: 'DM', label: 'Dominican' },
  { code: 'DO', label: 'Dominican (Dominican Republic)' },
  { code: 'EC', label: 'Ecuadorian' },
  { code: 'EG', label: 'Egyptian' },
  { code: 'SV', label: 'Salvadoran' },
  { code: 'GQ', label: 'Equatorial Guinean' },
  { code: 'ER', label: 'Eritrean' },
  { code: 'EE', label: 'Estonian' },
  { code: 'SZ', label: 'Swazi' },
  { code: 'ET', label: 'Ethiopian' },
  { code: 'FJ', label: 'Fijian' },
  { code: 'FI', label: 'Finnish' },
  { code: 'FR', label: 'French' },
  { code: 'GA', label: 'Gabonese' },
  { code: 'GM', label: 'Gambian' },
  { code: 'GE', label: 'Georgian' },
  { code: 'DE', label: 'German' },
  { code: 'GH', label: 'Ghanaian' },
  { code: 'GR', label: 'Greek' },
  { code: 'GD', label: 'Grenadian' },
  { code: 'GT', label: 'Guatemalan' },
  { code: 'GN', label: 'Guinean' },
  { code: 'GW', label: 'Bissau-Guinean' },
  { code: 'GY', label: 'Guyanese' },
  { code: 'HT', label: 'Haitian' },
  { code: 'HN', label: 'Honduran' },
  { code: 'HU', label: 'Hungarian' },
  { code: 'IS', label: 'Icelandic' },
  { code: 'IN', label: 'Indian' },
  { code: 'ID', label: 'Indonesian' },
  { code: 'IR', label: 'Iranian' },
  { code: 'IQ', label: 'Iraqi' },
  { code: 'IE', label: 'Irish' },
  { code: 'IL', label: 'Israeli' },
  { code: 'IT', label: 'Italian' },
  { code: 'JM', label: 'Jamaican' },
  { code: 'JP', label: 'Japanese' },
  { code: 'JO', label: 'Jordanian' },
  { code: 'KZ', label: 'Kazakhstani' },
  { code: 'KE', label: 'Kenyan' },
  { code: 'KI', label: 'I-Kiribati' },
  { code: 'KP', label: 'North Korean' },
  { code: 'KR', label: 'South Korean' },
  { code: 'KW', label: 'Kuwaiti' },
  { code: 'KG', label: 'Kyrgyzstani' },
  { code: 'LA', label: 'Lao' },
  { code: 'LV', label: 'Latvian' },
  { code: 'LB', label: 'Lebanese' },
  { code: 'LS', label: 'Basotho' },
  { code: 'LR', label: 'Liberian' },
  { code: 'LY', label: 'Libyan' },
  { code: 'LI', label: 'Liechtensteiner' },
  { code: 'LT', label: 'Lithuanian' },
  { code: 'LU', label: 'Luxembourgish' },
  { code: 'MG', label: 'Malagasy' },
  { code: 'MW', label: 'Malawian' },
  { code: 'MY', label: 'Malaysian' },
  { code: 'MV', label: 'Maldivian' },
  { code: 'ML', label: 'Malian' },
  { code: 'MT', label: 'Maltese' },
  { code: 'MH', label: 'Marshallese' },
  { code: 'MR', label: 'Mauritanian' },
  { code: 'MU', label: 'Mauritian' },
  { code: 'MX', label: 'Mexican' },
  { code: 'FM', label: 'Micronesian' },
  { code: 'MD', label: 'Moldovan' },
  { code: 'MC', label: 'Monegasque' },
  { code: 'MN', label: 'Mongolian' },
  { code: 'ME', label: 'Montenegrin' },
  { code: 'MA', label: 'Moroccan' },
  { code: 'MZ', label: 'Mozambican' },
  { code: 'MM', label: 'Myanmar' },
  { code: 'NA', label: 'Namibian' },
  { code: 'NR', label: 'Nauruan' },
  { code: 'NP', label: 'Nepali' },
  { code: 'NL', label: 'Dutch' },
  { code: 'NZ', label: 'New Zealander' },
  { code: 'NI', label: 'Nicaraguan' },
  { code: 'NE', label: 'Nigerien' },
  { code: 'NG', label: 'Nigerian' },
  { code: 'MK', label: 'Macedonian' },
  { code: 'NO', label: 'Norwegian' },
  { code: 'OM', label: 'Omani' },
  { code: 'PK', label: 'Pakistani' },
  { code: 'PW', label: 'Palauan' },
  { code: 'PS', label: 'Palestinian' },
  { code: 'PA', label: 'Panamanian' },
  { code: 'PG', label: 'Papua New Guinean' },
  { code: 'PY', label: 'Paraguayan' },
  { code: 'PE', label: 'Peruvian' },
  { code: 'PH', label: 'Filipino' },
  { code: 'PL', label: 'Polish' },
  { code: 'PT', label: 'Portuguese' },
  { code: 'QA', label: 'Qatari' },
  { code: 'RO', label: 'Romanian' },
  { code: 'RU', label: 'Russian' },
  { code: 'RW', label: 'Rwandan' },
  { code: 'KN', label: 'Kittitian and Nevisian' },
  { code: 'LC', label: 'Saint Lucian' },
  { code: 'VC', label: 'Vincentian' },
  { code: 'WS', label: 'Samoan' },
  { code: 'SM', label: 'Sammarinese' },
  { code: 'ST', label: 'Sao Tomean' },
  { code: 'SA', label: 'Saudi Arabian' },
  { code: 'SN', label: 'Senegalese' },
  { code: 'RS', label: 'Serbian' },
  { code: 'SC', label: 'Seychellois' },
  { code: 'SL', label: 'Sierra Leonean' },
  { code: 'SG', label: 'Singaporean' },
  { code: 'SK', label: 'Slovak' },
  { code: 'SI', label: 'Slovenian' },
  { code: 'SB', label: 'Solomon Islander' },
  { code: 'SO', label: 'Somali' },
  { code: 'ZA', label: 'South African' },
  { code: 'SS', label: 'South Sudanese' },
  { code: 'ES', label: 'Spanish' },
  { code: 'LK', label: 'Sri Lankan' },
  { code: 'SD', label: 'Sudanese' },
  { code: 'SR', label: 'Surinamese' },
  { code: 'SE', label: 'Swedish' },
  { code: 'CH', label: 'Swiss' },
  { code: 'SY', label: 'Syrian' },
  { code: 'TW', label: 'Taiwanese' },
  { code: 'TJ', label: 'Tajikistani' },
  { code: 'TZ', label: 'Tanzanian' },
  { code: 'TH', label: 'Thai' },
  { code: 'TL', label: 'Timorese' },
  { code: 'TG', label: 'Togolese' },
  { code: 'TO', label: 'Tongan' },
  { code: 'TT', label: 'Trinidadian and Tobagonian' },
  { code: 'TN', label: 'Tunisian' },
  { code: 'TR', label: 'Turkish' },
  { code: 'TM', label: 'Turkmen' },
  { code: 'TV', label: 'Tuvaluan' },
  { code: 'UG', label: 'Ugandan' },
  { code: 'UA', label: 'Ukrainian' },
  { code: 'AE', label: 'Emirati' },
  { code: 'GB', label: 'British' },
  { code: 'US', label: 'American' },
  { code: 'UY', label: 'Uruguayan' },
  { code: 'UZ', label: 'Uzbekistani' },
  { code: 'VU', label: 'Ni-Vanuatu' },
  { code: 'VA', label: 'Vatican' },
  { code: 'VE', label: 'Venezuelan' },
  { code: 'VN', label: 'Vietnamese' },
  { code: 'YE', label: 'Yemeni' },
  { code: 'ZM', label: 'Zambian' },
  { code: 'ZW', label: 'Zimbabwean' },
] as const;

export const POS_NATIONALITY_LABELS = POS_NATIONALITIES.map(({ label }) => label);

